### ISSUE TITLE
I get KotlinNullPointerException in some devices like TECNO N6S & Samsung Galaxies

### ISSUE THREAD

**Issue by JobGetabu** [rommansabbir/NetworkX#4]
```
Fatal Exception: kotlin.KotlinNullPointerException
       at com.rommansabbir.networkx.NetworkX.isNetworkAvailable(NetworkX.java:180)
       at com.rommansabbir.networkx.NetworkX.startObserving(NetworkX.java:144)
       at com.rommansabbir.networkx.NetworkX.startObserving(NetworkX.java:154)
       at com.rommansabbir.networkx.NetworkX$startObserving$1.invokeSuspend(NetworkX.java)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by rommansabbir** [comment]
Did you initialize properly? Can you post detail here?

**Comment by rommansabbir** [comment]
Mention your Studio Version & send the stacktrace. Thanks.

**Comment by JobGetabu** [comment]
I get this from Crashlytics
used AS 4.0, thats the full stacktrace

I attach listener to activity 
```
NetworkX.isConnectedLiveData().observe(this, {
            //...
        })
```

**Comment by rommansabbir** [comment]
Did you initialized CacheX properly in your application class?

**Comment by JobGetabu** [comment]
In the application class I have

```
 override fun onCreate() {
        super.onCreate()
        NetworkX.startObserving(this, NetworkXObservingStrategy.MEDIUM)
    }
```

**Comment by HishaBee** [comment]
Have the same issue. Is there any fix for this?

**Comment by rommansabbir** [comment]
Upgrade to the latest version.
