### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException on version 2.1.0 

### ISSUE THREAD

**Issue by yesidlazaro** [rommansabbir/NetworkX#8]
Fatal Exception: java.lang.NullPointerException
       at com.rommansabbir.networkx.core.NetworkXImpl.isNetworkAvailable(NetworkXImpl.java:151)
       at com.rommansabbir.networkx.core.NetworkXImpl.startObserving(NetworkXImpl.java:101)
       at com.rommansabbir.networkx.core.NetworkXImpl$1.invokeSuspend(NetworkXImpl.java:45)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

i am not getting this in my debug devices but i getting the report in firebase crashlytics. i am using kotlin 1.5.10, and the crash happens in android 7, 8, 9 

 i am calling the init method on my onCreate in the application class like this 

NetworkXCore.init(this, NetworkXObservingStrategy.HIGH)

**Comment by rommansabbir** [comment]
Will review soon. Thanks.

**Comment by yesidlazaro** [comment]
@rommansabbir any update here? thanks in advance
